export const columns = [
  {
    field: "id",
    headerName: "ลำดับ",
    minWidth: 80,
    hideSortIcons: "true",
    headerClassName: "header",
    cellClassName: "cellDark",
  },
  {
    field: "offerTypeName",
    headerName: "ประเภท",
    minWidth: 180,
    hideSortIcons: "true",
    headerClassName: "header",
  },
  {
    field: "offerResultName",
    headerName: "ผลการขอใบอนุญาต",
    width: 180,
    align: "left",
    hideSortIcons: "true",
    headerClassName: "header",
    cellClassName: "primary-cell",
  },
  {
    field: "licenseNo",
    headerName: "เลขที่ใบอนุญาต",
    width: 200,
    align: "left",
    hideSortIcons: "true",
    headerClassName: "header",
  },
  {
    field: "approveDate",
    headerName: "วันที่ คปภ. อนุมัติ",
    width: 160,
    align: "left",
    hideSortIcons: "true",
    headerClassName: "header",
  },
  {
    field: "receiveDate",
    headerName: "วันที่ได้รับแบบฟอร์ม",
    minWidth: 160,
    align: "left",
    hideSortIcons: "true",
    headerClassName: "header",
  },
  {
    field: "issueDate",
    headerName: "วันที่ออกบัตร",
    minWidth: 160,
    align: "left",
    hideSortIcons: "true",
    headerClassName: "header",
  },
  {
    field: "expireDate",
    headerName: "วันที่หมดอายุ",
    minWidth: 160,
    align: "left",
    hideSortIcons: "true",
    headerClassName: "header",
  },
];

export const columns_tab3 = [
  {
    field: "a",
    headerName: "ลำดับ",
    minWidth: 80,
    hideSortIcons: "true",
    headerClassName: "header",
    cellClassName: "cellDark",
  },
  {
    field: "b",
    headerName: "เลขที่กรมธรรม์",
    width: 200,
    hideSortIcons: "true",
    headerClassName: "header",
  },
  {
    field: "c",
    headerName: "ชื่อ-นามสกุล",
    width: 160,
    align: "left",
    hideSortIcons: "true",
    headerClassName: "header",
  },
  {
    field: "d",
    headerName: "จำนวนเงินเอาประกันภัย",
    width: 160,
    align: "left",
    hideSortIcons: "true",
    headerClassName: "header",
  },
  {
    field: "e",
    headerName: "วันที่เริ่มสัญญา",
    width: 160,
    align: "left",
    hideSortIcons: "true",
    headerClassName: "header",
  },
];
