export const SHOW_SEARCH_POPUP = "SHOW_SEARCH_POPUP";
export const HIDE_SEARCH_POPUP = "HIDE_SEARCH_POPUP";
export const SHOW_SEARCH_SCHEDULE_POPUP = "SHOW_SEARCH_SCHEDULE_POPUP";
export const HIDE_SEARCH_SCHEDULE_POPUP = "HIDE_SEARCH_SCHEDULE_POPUP";
//ทุก action ที่เรียก redux