export const SHOW_SEARCH_LOCATION_POPUP = "SHOW_SEARCH_LOCATION_POPUP";
export const HIDE_SEARCH_LOCATION_POPUP = "HIDE_SEARCH_LOCATION_POPUP";
export const SHOW_EDIT_SCHEDULE_POPUP = "SHOW_EDIT_SCHEDULE_POPUP";
export const HIDE_EDIT_SCHEDULE_POPUP = "HIDE_EDIT_SCHEDULE_POPUP";
export const SHOW_ALERT_POPUP = "SHOW_ALERT_POPUP";
export const HIDE_ALERT_POPUP = "HIDE_ALERT_POPUP";
export const SHOW_SEARCH_POPUP = "SHOW_SEARCH_POPUP";
export const HIDE_SEARCH_POPUP = "HIDE_SEARCH_POPUP";
export const SHOW_EDIT_LOCATION_POPUP = "SHOW_EDIT_LOCATION_POPUP";
export const HIDE_EDIT_LOCATION_POPUP = "HIDE_EDIT_LOCATION_POPUP";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";
export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const SHOW_SEARCH_SCHEDULE_POPUP = "SHOW_SEARCH_SCHEDULE_POPUP";
export const HIDE_SEARCH_SCHEDULE_POPUP = "HIDE_SEARCH_SCHEDULE_POPUP";
//ทุก action ที่เรียก redux
